### ISSUE TITLE
Grid Checkbox auto select 

### ISSUE THREAD

**Issue by tyjing** [atatanasov/gijgo#112]
The checkbox in grid table will auto tick without selecting anything after the table is loaded.
Not very sure how is it going to. 
Please help to solve it urgently

**Comment by atatanasov** [comment]
Could you provide code sample that I can use to replicate the issue

**Comment by tyjing** [comment]
Below is the code sample :)

```
<head>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/checkbox.min.css" rel="stylesheet" />
    <link href="~/Content/grid/grid.min.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.11.1.js"></script>
    <script src="~/Scripts/checkbox.min.js"></script>
    <script src="~/Scripts/grid/grid.min.js"></script>
</head>
<body>
    <div class="col-xs-12"> 
         <table id="ItemGrid"></table> 
    </div>

    <script>
var gridItem;
$(document).ready(function () {
        gridItem = $('#ItemGrid').grid({
            primaryKey: 'ItemId',
            dataSource: '/Admin/GetItemList',
            uiLibrary: 'bootstrap',
            selectionType: 'multiple',
            selectionMethod: 'checkbox',
            columns: [
                { field: 'No', width: 32 },
                { field: 'ItemId', sortable: true, hidden: true },
                { field: 'ItemCode', title: 'Item Code', sortable: true },
                { field: 'ItemName', title: 'Item Name', sortable: true },
                { field: 'ItemSpec', title: 'Item Spec', sortable: true },
                { field: 'DateAdded', title: 'Date Added', sortable: true },
            ],
            pager: { limit: 10, sizes: [10, 15, 20, 50, 100] },
        });
    });
    </script>
</body>
```

**Comment by atatanasov** [comment]
We fixed that in the new development version. You can find the new build at https://github.com/atatanasov/gijgo/tree/master/dist

**Comment by tyjing** [comment]
Thank you so much @atatanasov  
You have save my life :)

**Comment by tyjing** [comment]
Hey @atatanasov  i just realized that the updated version caused the pagination not function well.
Besides that, I added my own filter selection in the table, after i filtered the option, the checkboxes are automatically checked.

**Comment by atatanasov** [comment]
Could you send me a screenshot in order to see what is wrong with the pagination? Could you send me your code in order to see how the checkboxes are getting checked?
If you use modular build you have to add the dropdown when you are using pagination. This could be the issue.

**Comment by tyjing** [comment]
**First** error is after i filter the option checkboxes are checked.
![checkboxerror1](https://user-images.githubusercontent.com/30327028/28552952-a8a9e694-7123-11e7-9d1f-9b6a32543c78.gif)

**Second** error is after i sorted the column, checkboxes are checked.
![checkboxerror2](https://user-images.githubusercontent.com/30327028/28552965-be2382aa-7123-11e7-9d4e-93d8e677f15b.gif)

**Third** error is i just clicked on the pagination, it is overlaid by the textinput below and auto refresh the page.
![paginationoverlayerror](https://user-images.githubusercontent.com/30327028/28552990-e3f5f1ac-7123-11e7-8a3d-6b783dccd018.gif)

**Forth** error is after i selected the number of data shown in a page, the result is not shown
![paginationerror](https://user-images.githubusercontent.com/30327028/28553016-0d9e3384-7124-11e7-8044-6a58e4af9f3f.gif)


I have tried to import the dropdown and checkbox css & js to my project, the result is still the same.
my code sample is still the same as above.

**Comment by atatanasov** [comment]
I think that I fixed your issues. Could you get the latest version from https://github.com/atatanasov/gijgo/tree/master/dist and try again.

**Comment by tyjing** [comment]
The solution above solved the checkbox issues but the pagination is still unable to filter the result. 
![image](https://user-images.githubusercontent.com/30327028/28565211-1f0751ca-715e-11e7-8985-72ba67fa7cb3.png)

**Comment by atatanasov** [comment]
I downloaded the latest build from https://github.com/atatanasov/gijgo/tree/master/dist (I have a changes last days) and everything works fine. Could you download everything again and try again. You could be with old version of the dropdown.js and .css.
You can also exclude dropdown.js and .css and you grid is going to use a native browser dropdown where you are not going have such issues.

**Comment by tyjing** [comment]
@atatanasov  can you please tell me which is the .css and .js file i need to import to my project? 
Currently i only input grid.css, grid.js, gijgo.css, gijgo.js, dropdown.js and dropdown.css. 
But i get the following error in the console.
![image](https://user-images.githubusercontent.com/30327028/28679137-da7da89c-7324-11e7-9741-ed402ec7a747.png)

**Comment by atatanasov** [comment]
You can use just gijgo.js gijgo.css and jquery and that's all. If you use modular build you need to add core.js core.css and every component like grid with js and css file separately. Gijgo.js combine all components (grid, tree, etc.) Into one js file. It is up to you

**Comment by tyjing** [comment]
@atatanasov  is there any sequence for your js? 

```

<script src="~/Scripts/jquery-1.11.1.min.js"></script>
            <script src="~/Scripts/bootstrap.min.js"></script>
        <script src="~/Scripts/respond.min.js"></script>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" />
        <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <link href="~/Content/main.css" rel="stylesheet" />
    <link href="~/Content/sb-admin-2.css" rel="stylesheet" />
    <link href="~/Content/metisMenu.min.css" rel="stylesheet" />
    <link href="~/Content/sweetalert.css" rel="stylesheet" />
    <link href="~/Content/jquery.bootgrid.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link href="~/Content/gijgo.min.css" rel="stylesheet" />
    <link href="~/Content/datepicker.css" rel="stylesheet" />
    <script src="~/Scripts/sb-admin-2.min.js"></script>
    <script src="~/Scripts/metisMenu.min.js"></script>
    <script src="~/Scripts/sweetalert.min.js"></script>
    <script src="~/Scripts/jquery.bootgrid.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="~/Scripts/jquery.maskedinput.min.js"></script>
    <script src="~/Scripts/gijgo.min.js"></script>
    <script src="~/Scripts/moment.min.js"></script>
    <script src="~/Scripts/bootstrap-datepicker.js"></script>
```

this is my current imported .js and .css 
the pagination still not function

**Comment by atatanasov** [comment]
The order of the files doesn't matter. Could you compare your code with our ASP.NET examples where we use the latest gijgo.js and the pagination works fine. Here is the code: https://github.com/atatanasov/gijgo-asp-net-examples
