### ISSUE TITLE
grid library conflict with jquery.ui

### ISSUE THREAD

**Issue by pentexsoft** [atatanasov/gijgo#222]
When using bootstrap4 & fontawesome for grid libraries along with jquery ui, the jquery ui file ( jquery-ui.css) prevents the fonts from showing in column type:'icon' in the grid.
the default icon '>' shows instead of the fontawesome icon.

**Comment by atatanasov** [comment]
This should be fixed in the new version 1.7.2 that is released today. Could you try the new version.

**Comment by pentexsoft** [comment]
v1.7.2 still does not work with the icon column type.
below still shows the standard arrow up icon instead of the fa-pencil.

example:
  { title: '', field: 'Edit', width: 38, type: 'icon', icon: 'fa fa-pencil ', tooltip: 'Edit', events: { 'click': CompanyEquipment_Edit } },

**Comment by atatanasov** [comment]
The issue is probably somewhere else. It works in this example http://gijgo.com/Temp/f5e398fe-ddb6-4da6-a3bd-5dc9e749895c.html

You can always use http://gijgo.com/grid/configuration/column.renderer in order to add the column manually if type icon is problematic.

**Comment by pentexsoft** [comment]
this issue is with jquery.ui  
the example you have listed above does not have jquery ui in it.
this is the file that is causing the issue: jquery-ui.min.css.
I also understand I can use another technique, but wanted to report this as jquery.ui is a common plugin.

**Comment by atatanasov** [comment]
I included jqueryui in the example below, but everything looks good.

http://gijgo.com/Temp/90543f86-7dcf-4a88-9758-2081c422904d.html

**Comment by pentexsoft** [comment]
I am using bootstrap 4. it still has a problem.

here are the script files I have tested with:

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/gijgo/1.7.2/combined/css/gijgo.min.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gijgo/1.7.2/combined/js/gijgo.min.js"></script>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>

**Comment by atatanasov** [comment]
I saw the issue. We fixed that in the new development version.

**Comment by Toniazada** [comment]
Please?  help  grid library conflict with jquery.ui  I use Gijgo JavaScript Library v1.9.11 and jQuery UI - v1.12.1 (url)

 after click Edit type DATE empty
