### ISSUE TITLE
DatePicker - pressing enter when input is empty breaks control

### ISSUE THREAD

**Issue by jontcarroll** [atatanasov/gijgo#301]
I am using 1.9.1. When pressing enter on the input, if the input is empty and the value hasn't changed since initialization, the input will display NaN/NaN/NaN and all functionality of the datepicker is broken until re-initialization. This is reproduce-able on the example page as well.

**Comment by atatanasov** [comment]
We fixed that in the new development version. You can find the new build in the dist folder in github. Thanks for reporting this.

**Comment by Pyre1** [comment]
I'm using 1.9.11 version in my asp.net application and this problem still reproduces
